server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8899
  servlet:
    context-path: /api/v1/swift

spring:

  resources:
    static-locations: classpath:/resources/,classpath:/static/

  servlet:
    multipart:
      max-file-size: 3000MB #单文件上传最大大小，默认1Mb
      max-request-size: 30000MB #多文件上传时最大大小,默认10Mb

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.ict.cloudic.*: debug

keystone:
  username: "admin"
  password: "smartcore.123"
  url: "http://192.168.243.10:5000/v3/auth/tokens"
  region: "RegionOne"
  domain: "default"

service:
  object: "swift"
  interface: "public"
